---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nginx
spec:
  controllerName: gateway.nginx.org/gatewayclass
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: web-gw
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
      # Optional: if your controller honors this, you can hint a VIP
      addresses:
        - type: IPAddress
          value: 192.168.2.210  # optional hint; controller may ignore
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zed-lab-web
spec:
  parentRefs:
    - name: web-gw
  # hostnames: ["your.domain.com"]  # optional
  rules:
    - backendRefs:
        - name: zed-lab-web
          port: 80
