# 00-kube-vip-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vip
  namespace: kube-system
data:
  enableLoadBalancer: "true"
  lbEnable: "true"
  vip_leaderelection: "true"
  provider: "kube-vip"
  # IMPORTANT: use a single L2 subnet that matches your nodes' LAN
  range-global: "192.168.0.240-192.168.0.245"
---
# 10-kube-vip-cloud-provider-sa-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kube-vip-cloud-controller
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "nodes", "pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-vip-cloud-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-cloud-controller
subjects:
  - kind: ServiceAccount
    name: kube-vip-cloud-provider
    namespace: kube-system
---
# 20-kube-vip-cloud-provider-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-vip-cloud-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-cloud-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-cloud-provider
    spec:
      serviceAccountName: kube-vip-cloud-provider
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      containers:
        - name: kube-vip-cloud-provider
          image: docker.io/kubevip/kube-vip-cloud-provider:v0.0.12
          imagePullPolicy: IfNotPresent
          command: ["/kube-vip-cloud-provider"]
          args:
            - --leader-elect-resource-name=kube-vip-cloud-provider
            - --leader-elect-resource-namespace=kube-system
            - --enableLoadBalancerClass=true
          env:
            - name: KUBEVIP_NAMESPACE
              value: kube-system
            - name: KUBEVIP_CONFIGMAP
              value: kube-vip
            - name: KUBEVIP_SVC_LB_POLL
              value: "true"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
