apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-vip-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-vip-test
  template:
    metadata:
      labels:
        app: my-app-vip-test
    spec:
      containers:
        - name: web
          image: docker.io/nginxdemos/hello:latest   # lightweight demo web server
          ports:
            - containerPort: 8080
          env:
            - name: NGINX_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
# Traefik IngressRoute (if CRDs installed) OR standard Ingress below
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-vip-test
                port:
                  number: 80
