---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain
provisioner: driver.longhorn.io
reclaimPolicy: Retain                 # keep the PV/data if the PVC is deleted
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "3"               # adjust to your Longhorn policy
  staleReplicaTimeout: "30"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]      # typical for single-writer volumes
  resources:
    requests:
      storage: 10Gi                   # size of the volume
  storageClassName: longhorn-retain
  volumeMode: Filesystem
