apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-replica-3
  # IMPORTANT: Longhorn must be installed for this to work.
provisioner: driver.longhorn.io
parameters:
  # Sets the number of copies of your data (3 is recommended for high availability).
  numberOfReplicas: "3" 
  staleReplicaTimeout: "2880" # 48 hours in minutes
reclaimPolicy: Retain # Retain the volume data even if the PVC is deleted
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zed-lab-web-pvc
  labels:
    app: zed-lab-web
spec:
  # Allows a single node/pod to read and write to the volume at a time.
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-replica-3
  resources:
    requests:
      storage: 5Gi # Request 5 Gigabytes of storage
